version: '3.8'

services:
  reservations-db:
    container_name: reservations-db
    image: postgres:16.1
    ports:
      - '5555:5432'
    environment:
      POSTGRES_DB: reservations
      POSTGRES_USER: reservations_user
      POSTGRES_PASSWORD: reservations_psw
    restart:
      unless-stopped
