spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5555/reservations'
    username: 'reservations_user'
    password: 'reservations_psw'
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: validate
        format_sql: false
  liquibase:
    change-log: 'classpath:db/liquibase-changelog-master.xml'
    contexts: 'test-data'
