version: '3.8'

services:
  reservations-db:
    container_name: reservations-db
    image: postgres:${DB_VERSION}
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart:
      unless-stopped
    networks:
      - reservations_net

networks:
  reservations_net:
